name: Get workflow job id

description: Get the ID of the workflow job that is currently running.

inputs:
  github-token:
    description: GITHUB_TOKEN
    required: true

outputs:
  job-id:
    description: The retrieved workflow job id
    value: ${{ steps.get-job-id.outputs.job-id }}

runs:
  using: composite
  steps:
    - shell: bash
      id: get-job-id
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        set -x
        python3 -m pip install requests==2.26.0
        GHA_WORKFLOW_JOB_ID=$(python3 .github/scripts/get_workflow_job_id.py "${GITHUB_RUN_ID}" "${RUNNER_NAME}")
        echo "::set-output name=job-id::${GHA_WORKFLOW_JOB_ID}"
