name: Upload test stats

on:
  workflow_run:
    workflows: [pull, trunk, periodic]
    types:
      - completed

jobs:
  upload-test-stats:
    runs-on: [self-hosted, linux.2xlarge]

    steps:
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@master@${{ github.sha }}

      - uses: actions/setup-python@v3

      - run: pip install requests==2.26

      - name: Upload test stats
        env:
          WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id }}
        run: python tools/stats/upload_test_stats.py --workflow-run-id "${WORKFLOW_RUN_ID}"
